### ISSUE TITLE
"deadlock" on actor.send

### ISSUE THREAD

**Issue by spumer** [spumer/dramatiq-kombu-broker#5]
```
Thread 463 (idle): "ThreadPoolExecutor-1_6"
    retry_over_time (kombu/utils/functional.py:332)
    retry (dramatiq_kombu_broker/connection_holder.py:42)
    ensure (dramatiq_kombu_broker/broker.py:277)
    _ensure_queue (dramatiq_kombu_broker/broker.py:295)
    declare_queue (dramatiq_kombu_broker/broker.py:214)
    enqueue (dramatiq_kombu_broker/broker.py:305)
    send_with_options (dramatiq/actor.py:167)
    enqueue_tasks (dramatiq_batch_runner.py:83)
    __call (dramatiq/actor.py:182)
    call (dramatiq_scheduler.py:53)
    run_job (apscheduler/executors/base.py:125)
    inner (contextlib.py:81)
    run (concurrent/futures/thread.py:58)
    _worker (concurrent/futures/thread.py:83)
    run (threading.py:982)
    run (sentry_sdk/integrations/threading.py:70)
    _bootstrap_inner (threading.py:1045)
    _bootstrap (threading.py:1002)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dramatiq_kombu_broker/broker.py", line 231, in _declare_dq_queue
    queue = self.topology.declare_delay_queue(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dramatiq_kombu_broker/topology.py", line 161, in declare_delay_queue
    return self._declare_queue(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dramatiq_kombu_broker/topology.py", line 120, in _declare_queue
    queue.declare()
  File "/usr/local/lib/python3.11/site-packages/kombu/entity.py", line 617, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/usr/local/lib/python3.11/site-packages/kombu/entity.py", line 626, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/usr/local/lib/python3.11/site-packages/kombu/entity.py", line 655, in queue_declare
    ret = channel.queue_declare(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/amqp/channel.py", line 1156, in queue_declare
    self.send_method(
  File "/usr/local/lib/python3.11/site-packages/amqp/abstract_channel.py", line 70, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.11/site-packages/kombu_pyamqp_threadsafe/__init__.py", line 267, in wrapper
    raise OSError("Socket closed")
OSError: Socket closed
```

**Comment by spumer** [comment]
This possible due `KombuBroker.max_enqueue_attempts` are None by default

And affects cases where you only produce messages. If you have consumers in same process your are not afftected.

Affected case is producing messages by cron.
